### ISSUE TITLE
Several issues with latest Fullcalendarcomponent 1.1.1

### ISSUE THREAD

**Issue by leokady** [Servoy/fullcalendarcomponent#3] opened 2018-01-12 21:29 UTC
Fullcalendarcomponent 1.1.1
Some issue:
1. Top grid(on the calendar) for allDay area events not alignment with hours events grid(on the week and day view )
2. When I click on the day cell at left(small calendar) the callback function return me a day before(on the right calendar the date is correct)
3. The scrollTime property not working.  I set as  scrollTime: "13:00:00" in Calendar options by default , but it show me all events.
4. Please add onRightDayClick(make a same as on the onDayClick) to exclude windows popup.

**Comment by paronne** [comment] 2018-01-15 09:47
Hi,

regarding the issue you have been found.

1. Unfortunately that is an issue of the fullcalendar itself which has not been solved with the JQuery library versions shipped by Servoy. The fix requires an update of the JQuery lib which can probably be done for the next minor release of Servoy (8.3). You can watch the follow up case i have created https://support.servoy.com/browse/SVY-12047
2. I am not able to replicate your issue in our sample solution. You can try yourself in our demo server
https://demo.servoy.com/solutions/sampleGallery/index.html?m=showSample&a=fullcalendarComponentProvider
You can switch the right calendar to the Daily view, any time you select a date from the left calendar it always shows the correct selected date into the right calendar. Can you provide me more info, and eventually also a sample solution if is still reproducible on your side ?
3. The scrolltime doesn't hide other timeslots but simply moves the scrollbar to the specified time (if any scrollbar is visible) To hide time blocks use minTime and maxTime https://fullcalendar.io/docs/agenda/minTime/
4.  We will not provide onDayRightClick event since the fullcalendar library itself doesn't support any onDayRightClick event itself. 

Regards,
Paolo

**Comment by leokady** [comment] 2018-01-17 17:02
Hi,
- 1st Issue. I am not sure that alignment connected with JQuery. The problem is scrollbar on the bottom part of calendar and upper part don't have it.
![image](https://user-images.githubusercontent.com/31049550/35054999-0b1e5b56-fb7c-11e7-9312-aa5f98049bc9.png)
-  2second issue. The demo what you referenced works fine. I download a demo from https://github.com/Servoy/fullcalendarcomponent/wiki and it seems this version has a problem.  I export and attach a demo version from my computer(i created a 
[fullcalendarComponent$demo.zip](https://github.com/Servoy/fullcalendarcomponent/files/1639865/fullcalendarComponent.demo.zip)
zip file)

**Comment by paronne** [comment] 2018-01-22 13:19
Hi,

if i understand you correctly, the issue #1 is that you cannot scroll above 7.00.00 AM in the calendar ?
That is not an issue but is demonstrating one of the features of the fullcalendar (minTime); You have full control on which hours to show in the week and day view, and you can also decide where the scrollbar can start from.
The JQuery issue i am referince to is that the all day event is not properly aligned with the day hours in the week view.

About issue #2, the wiki page was referencing the demo solution of the previous release. Wiki is now updated with the reference to the latest releases.

Regards,
Paolo

**Comment by leokady** [comment] 2018-01-22 19:06
Hi,
   No isuue#1 not about the scrolling. On the calendar you have 2 grids: one for all days event and other one by hours. So these  2 grids not alignment in the week view, the cell from upper grid shift to right on the width of scroolbar from bottom grid.
![image](https://user-images.githubusercontent.com/31049550/35238942-0c9cf8d4-ff7d-11e7-8d3b-99e4d7bb2d31.png)

  Issue #2 . I doownload a new demo solution, instal in my developer,delete old one and imported a new one. I have a same issue , if Click on the january 31 the right calendar open for january30(in the day view)
![image](https://user-images.githubusercontent.com/31049550/35239051-5a4f0dd8-ff7d-11e7-943d-2891e16511c7.png)

**Comment by paronne** [comment] 2018-01-23 14:04
Hi,

the issue #1 is then the JQuery issue i mentioned in first place.

About the issue #2 i was finally able to replicate it; the issue is related to the timezone, i will keep the case open and look into it as soon as possible.

Regards,
Paolo

**Comment by paronne** [comment] 2018-01-24 16:46
Hi, the issue #2 is now solved; will be available on next release.
I have created a new case to track the issue #1 (https://github.com/Servoy/fullcalendarcomponent/issues/4)
I will now close this issues.

Regards,
Paolo

**Closed by paronne** 2018-01-24 16:46 UTC
